class Locators(object):
    LOGIN_FIELD = "//input[@id='identifierId']"
    LOGIN_BUTTON_F = "//*[@id='identifierNext']/span/span"
    PASSWORD_FIELD = "//input[@name='password']"
    LOGIN_BUTTON_S = "//*[@id='passwordNext']/span/span"
    INPUT_MAIL = "//*[@title='Входящие']"
    FIND_MAIL_FIELD = "//input[@aria-label='Поиск в почте']"
    FIND_MAIL_BUTTON = "//button[@aria-label='Поиск в почте']"

    """
    LOGIN_ERROR_TEXT = "//div[@id='mCSB_2_container']//span"
    CLOSE_POPUP = "//div[contains(@class, 'z-window-welcome-close')]"
    TRAIDER_ICON = "//img[@title='test01 (Трейдер)']"
    TRAIDER_DROPLIST = "//input[@value='Трейдер']"
    TRAIDER_ITEM = "//li/span[contains(text(), 'Трейдер')]"
    MARKET_ICON = "//img[@title='Рынок']"
    MARTET_ITEMS = "//table[contains(@class, 'menu-active-item2')]//span[contains(@class, 'menu-item-fnt')]"
    CREATE_TIME_FROM = "(//input[@class='z-datebox-input'])[1]"
    CREATE_TIME_TO = "(//input[@class='z-datebox-input'])[2]"
    DB_SWITCHER = "//label[@class='z-switcher-content']"
    REFRESH = "//a[contains(@title, 'обновление')]"
    SAVE_IN_CSV = "//a[contains(@title, 'csv')]"
    CALCULATIONS_FROM = "(//input[@class='z-datebox-input'])[3]"
    CALCULATIONS_TO = "(//input[@class='z-datebox-input'])[4]"
    OVERLAY = "//div[@class='z-apply-mask']"
    DEAL_LIST_ITEM = "//tr[contains(@class, 'z-listitem')]"
    """
